version: "3"

services:
  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats

  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn start"
    links:
      - api

  processor:
    build: ./processor
    volumes:
      - ./processor:/usr/src/app
      - ./shared:/usr/src/shared
    links:
      - nats
    environment:
      - "NATS_ADDRESS=nats://nats:4222"
    depends_on:
      - nats
    command: bash -c "bash ./wait-for-it.sh nats:4222 -- cargo watch -x run"

  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
      - ./shared:/usr/src/shared
    links:
      - nats
    environment:
      - "NATS_ADDRESS=nats://nats:4222"
    depends_on:
      - nats
    command: bash -c "bash ./wait-for-it.sh nats:4222 -- cargo watch -x run"
