[package]
name = "test_processor"
version = "0.0.1"

[dependencies]
test_shared = { path = "../shared" }
serde = "1.0.77"
serde_derive = "1.0.99"
serde_json = "*"
nats = "0.3.2"
dotenv = "0.9.0"

[dependencies.redis]
version = "*"
